= My teaching philosophy


I am still learning as I go along, but there are some themes that seem to make sense for me as a teacher.
To summarize.

- Holistic 全体的 -- Learning should be connected to life, context, and personality  
- Empathetic 共感 -- A good relationship of understanding between a learner and a teacher helps everyone stay motivated, and feel safe to experiment and improve. Trying to understand learners thoughts, feeling and motivations helps in making lessons that are best for them.
- Social 社会 -- Learning is a social process. Knowledge is socially constructed and used, so it should be learned socially
- Independent 独立 -- In a ever changing world, learning doesn't finish with school. I encourage learners to build skills to learn by themselves.
- Fun -- Learning shouldn't be a chore. Fun isn't always without learning.   
- Respect 尊敬 -- I respect my students, and I want them to respect themselves and their fellow learners. 
+ 
*Some influences:*

http://iteslj.org/Articles/Weschler-UsingL1.html[Uses of Japanese (L1) in the English Classroom:] + 
http://eflmagazine.com/cooperative-learning/[COOPERATIVE LEARNING] + 
http://readingfirst.scoe.net/documents/LEASession3.pdf[Teaching is a cultural practice]